<a href="https://colab.research.google.com/github/nineteetwo/project-f/blob/main/pytorch_ders0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
#testing collab if everything works
#don't forget to change the runtime type to GPU.
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
!nvidia-smi

2.8.0+cu126
/bin/bash: line 1: nvidia-smi: command not found


Intro to Tensors

creating tensors

In [68]:
#scalar
scalar = torch.tensor(8)
scalar


tensor(8)

In [69]:
#ndim shows that how many dimentions is there.
scalar.ndim

0

In [70]:
#get tensor back as a python int
print(scalar.item())

8


In [71]:
#Vectors
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [72]:
vector.ndim

1

In [73]:
vector.shape

torch.Size([2])

In [74]:
#MATRIX
MATRIX = torch.tensor([[7,8],[8,9]])
MATRIX.ndim

2

In [75]:
MATRIX[0]


tensor([7, 8])

In [76]:
MATRIX.shape

torch.Size([2, 2])

In [77]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[9,10,11]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 9, 10, 11]]])

In [78]:
TENSOR.shape

torch.Size([1, 3, 3])

In [79]:
TENSOR.ndim

3

##Random Tensors
### Why random tensors because the way the ml work is like this:


```
# Random numbers ->
      while True:
         look at data
         update random numbers -> look at data
```



In [80]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.9067, 0.2723, 0.6011, 0.6923],
         [0.5535, 0.1980, 0.7134, 0.1395],
         [0.3465, 0.3090, 0.7151, 0.3111]]])

In [81]:
#random image size tensor
#224x224 red green blue picture
random_img_size_tensor = torch.rand(size=(3,224,224))
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [82]:
#zeroes and ones
zerose = torch.zeros(size=(1,3,4))
ones = torch.ones(size=(2,3,4))
print(zerose)
print(ones)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [84]:
#default datatype is float. take a look here
random_tensor.dtype, ones.dtype

(torch.float32, torch.float32)